<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <ProjectReference Include="..\Noto.Core\Noto.Core.csproj" />
    <ProjectReference Include="..\Noto.Platform\Noto.Platform.csproj" />
    <ProjectReference Include="..\Noto.Providers\Noto.Providers.csproj" />
    <ProjectReference Include="..\Noto.Sync\Noto.Sync.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="Help\topics.json" LogicalName="Noto.App.Help.topics.json" />
  </ItemGroup>
</Project>
