<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
    <ProjectReference Include="..\Noto.App\Noto.App.csproj" />
    <ProjectReference Include="..\Noto.Data\Noto.Data.csproj" />
    <ProjectReference Include="..\Noto.Platform\Noto.Platform.csproj" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
